### ISSUE TITLE
Vanilla.js

### ISSUE THREAD

**Issue by zimt28** [zurb/foundation-apps#136]
As the full feature set of foundation-apps is withheld to those using AngularJS, it would be nice if we had a vanilla.js version of foundation-apps. It then would be much easier to use all the components with other frameworks like ember, backbone, meteorjs (blaze) and so on, and people who don't use any framework at all could use it as well.

Decisions have to be made but this kinda limits the audience in my opinion :)

(Maybe it's not that hard to get things working with vanilla.js? I'll look into that later)

**Comment by johntron** [comment]
I'll always appreciate an open-source project like this (thanks and congrats on 1.0!), but let's be honest:
> you should be able to port the interactions by yourself without a problem

If you mean the work is trivial, then yes, but it's still a ton of work.

Here's just the beginning:
1. Almost completely refactor the Angular controllers. Unfortunately, this would be pretty difficult, because of the heavy reliance on Angular idioms like $scope, resource loading, dependency management, templating, object lifecycles, etc.
2. Remove some angular-specific markup from templates or find a template library that works. You could leave a lot of the markup in if you don't mind the clutter. Projects with existing template libraries may have a hard time with this.
3. Incorporate a builder or resource loader that will work with 1 and 2. This would take some work, but could be done on new projects; however, existing projects probably already have tools like this, and integrating the two may be nearly impossible.
4. Incorporate your own SASS transpiler - not so bad.
5. (optional) Update dependencies/skeletons to make the CLI tools work. Probably not too bad if you don't mind using gulp and npm.

Individual components could be converted as needed, but for someone like me it would probably be easier (and preferred) to just write the component from scratch.

If this project intends to support vanilla JavaScript it should start now, because continuing to rely on Angular will make it harder with each commit. It's fine if you don't want to support it, just don't mislead people. Maybe try organizing a team to port the framework? 

JS will be around for years to come, but it's frameworks and tools rise and fall very quickly, so starting with a good foundation (get it?) seems like a better strategy.

**Comment by johntron** [comment]
Oh, here's another idea - document how to use  some of the key components in isolation - vertical grids alone would be killer.

**Comment by chapinkapa** [comment]
You can pull out the css and it should work fine.

I imagine that they started using angular because foundation for apps was a concept, and the easiest way to deliver on that concept was using angular. It would be very difficult to reproduce what they did in vanilla javascript without: loosing key features, relying on a different framework, or creating their own framework.

**Comment by zimt28** [comment]
I'm sure it would be possible to port the code to another framework. What I find so bad about this decision is, that everyone who doesn't or even can't use Angular will not be able to use it. If they had just used JavaScript, Angular people could still use it, but *everyone else* could, too.

**Comment by btknorr** [comment]
Why is issue closed?  Please reopen.  We a are big fans of Foundation but do not like Angular at all.  Please provide a vanilla js version.

**Comment by tatemz** [comment]
@chapinkapa I also think the mentality/philosophy shift from raw JS to frontend frameworks is the idea they are trying to share with the world. Just like they are trying to shift the philosophy on browser support (by supporting only IE 10+).

I believe Zurb's goal is to lead, not necessarily to follow. Thus far, they have shown good faith in balancing quality innovation with standard practices/procedure.
