### ISSUE TITLE
modals callout

### ISSUE THREAD

**Issue by stryju** [zurb/foundation-apps#332]
currently, there's no way to create a "dynamic" modal - it needs to be present on the page and identified by element's ID

why not [use](https://github.com/btford/angular-modal) (or create) a service that generates dynamic modals? potentially, a lot of elements won't be present in the DOM, until really needed.

---

also, a better support for animations is in order (currently there's a flickering bug - call out a modal and then click several times next to it rapidly, within 3s - this number sounds familiar :wink: )

**Comment by AntJanus** [comment]
Good idea on that. There's somewhat of a rift between the element usage since we want to support both developers that don't know Angular well but want to use the more dynamic features like modals, notifications, etc. and developers that already know Angular want more power-user features.

Features for the latter type of a user are definitely lacking because, as you said, pretty much all the components should have services that create them and don't require in-template directives. If I have time, I'll go ahead and prototype a modal service that we can also port to other components.

**Comment by AntJanus** [comment]
Modal factory is now available in the code under, you guessed it, `ModalFactory`
