### ISSUE TITLE
foundationApi is not defined

### ISSUE THREAD

**Issue by vincentmorneau** [zurb/foundation-apps#373]
I'm trying to use the foundationApi for a simple notification using the following HTML:

```<zf-notification-set id="main-notifications"></zf-notification-set>```

And with the following call:
```foundationApi.publish('main-notifications', { title: 'Test', content: 'Test2' });```

But it's returning this error in the console:
VM11592:2 Uncaught ReferenceError: foundationApi is not defined

This is as instructed in the docs here : http://foundation.zurb.com/apps/docs/#!/notification

**Comment by AntJanus** [comment]
@vincentmorneau have you had a chance to look over what I wrote and try it out?

**Comment by vincentmorneau** [comment]
@AntJanus Not yet but I will tonight or tomorrow!

**Comment by AntJanus** [comment]
@vincentmorneau yes, there is a way to launch a modal page and just about every other FA component programmatically.

Unfortunately, it *does* require more thorough AngularJS knowledge especially of controllers. I wrote a [beginner's guide to angular](http://antjanus.com/blog/web-development-tutorials/front-end-development/comprehensive-beginner-guide-angularjs/) last year that can give you a quick crash-course to everything Angular. That may help you out.

Here's a sample controller that may do what you're thinking of and once you grasp the basics of Angular, you'll have an easier time understanding what's going on and figuring out better ways of opening modals, etc. :

````js
angular.module('application')
   .controller('MyController', ['FoundationApi', function(FoundationApi) {
     this.openModal = function() {
      FoundationApi.publish('my-modal-id', 'show');
    };
}]);
````
and with accompanying HTML:

````html
<div ng-controller="MyController as myCtrl">
   <a href="#" ng-click="myCtrl.openModal()">open modal</a>
</div>
````

Since this is no longer an issue on a bug, I'll go ahead and close this out but feel free to comment on the issues with any further questions.
