### ISSUE TITLE
Providing first class support for <button> and <input type='button>

### ISSUE THREAD

**Issue by davidgeary** [zurb/foundation-apps#412]
It seems a bit odd that all of the support for buttons is based on them being defined using `<a>` elements.  I appreciate that these are quite flexible in their use and styling, and I'm sure people more expert than me will be able to explain why they're preferred.  But isn't there any justification for supporting `<button>`, `<input type="button">` and/or `<input type="submit">`, considering that they're arguably more semantically appropriate?

The latter are able to be given the basic styling using `class="button"` but a number of use-cases fail due to the CSS being defined with specific reference to the `<a>` element.  For example, post-fix buttons don't clear the default `margin` setting if you use `<button>`, resulting in the `<input>` element extending down:

```html
<span class="inline-label">
	<input type="search" placeholder="Search a thing">
	<button type="button" class="button">Search</button>
</span>
```

Would it be simple/logical to replace the references to `a` in the CSS with `.button`, which would then apply the styling regardless of the element used (and avoid the need for [explanatory comments](https://github.com/zurb/foundation-apps/blob/master/scss/components/_forms.scss#L174))?

**Comment by gakimball** [comment]
The issue is trying to interconnect the components when you don't know what the class names could be. Because we allow the user to write their own class names with the mixins, you don't know if that button will actually be `.button`, or `.custom-button-class` or something else.

In this specific case, it's probably fine to modify the selector to also look for `input[type="submit"]`, `input[type="button"]`, and `button` as well, because the use case of the `.inline-label` element is *very* specific—it's meant for inputs, buttons, labels, and nothing else.

**Comment by davidgeary** [comment]
Of course!  Good point - I'd overlooked the use of custom button classes replacing `.button`.

Button groups would need updating too though (and possibly iconic?).

**Comment by gakimball** [comment]
Yeah, button groups would need updating, and there may be a few other edge cases as well. Foundation 5 has a few blind spots like that actually. It's *really* hard sometimes to combine UI components when you don't know what their class name is ;)

Iconic is a unique case because the JavaScript always adds the `.iconic` class, so we don't have to worry about that one changing.
