### ISSUE TITLE
Google Map only shows in app refresh in Browser

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-apps#413]
I am embedding a Google Map inside a template page.
Map JS is stored inside a js file in my asset folder.
It is being pulled in using "onload" e.g.:
div id="map-canvas" onload="loadMap();"

This works when the page is reloaded in the browser,
but not when viewing the app as the page does not reload.

I tried using ng-include to load in the entire html block for the Google Map,
thinking that that might cause the content to be reloaded but that’s not working.

Is there a way to load content into a page and have it re-initialize, like what happens when you refresh the browser?

I am just using the standard controllers as I am not a js expert.

From looking online into "Angular JS Google Map" I see people have solved the problem using ng-if.
Is there something like this in Foundation-Apps.

**Comment by gakimball** [comment]
You can use any existing Angular library with Foundation for Apps. As you've figured out, normal JavaScript libraries don't work because single-page app frameworks are always swapping in and out HTML. Most plugins are designed to be initialized once, when the page loads and all the HTML is assumed to be there.

The Angular UI project has a lot of good libraries, including a [Google Maps](http://angular-ui.github.io/angular-google-maps/#!/) one you may be interested in.

**Comment by designchief** [comment]
Thanks for the reply, I know it wasn’t really an issue with the Apps code. 

i would love to see some more granular explanation of the Angular JS and examples on how to use this for us JS newbies...

I will check out the library you mentioned, thanks again.
