### ISSUE TITLE
Apply google material design for zurb components

### ISSUE THREAD

**Issue by bastienJS** [zurb/foundation-apps#429]
This is your button: http://foundation.zurb.com/docs/components/buttons.html

This is the competitions buttons:

https://material.angularjs.org/#/demo/material.components.button
https://www.polymer-project.org/components/paper-button/demo.html

Please implement material design for your buttons! My user like it! :P

**Comment by gakimball** [comment]
Material Design is a very opinionated style guide, which is good for what it's doing, but it's not the role of our framework to make all of those decisions related to layout, hierarchy, and styling. Because of that, we won't be skinning any of the Foundation frameworks to look like Material.

However, if *you* would like to write a Material theme and open source it, we can promote it for you :)

**Comment by vertbranding** [comment]
The link for polymer-project:
https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html

**Comment by ivanjaros** [comment]
Yes, I would also like some style that would extend the basic foundation styling with MD. Not just buttons.

**Comment by rbecheras** [comment]
Thanks @rmilushev for the link to the polymer project. 

And here the foundation theme project:

> Material Design version of Foudation for Sites by Zurb
> http://eucalyptuss.github.io/material-foundation/
