### ISSUE TITLE
Plans for further inclusion of Foundation for Sites modules?

### ISSUE THREAD

**Issue by etcook** [zurb/foundation-apps#441]
Are there plans to further include more modules from Foundation for Sites? How compatible are they with Foundation for Apps?

**Comment by gakimball** [comment]
In theory any of the basic Sites components that don't require any JavaScript will work just fine, since it's just CSS. There's also an [Angular library](http://pineconellc.github.io/angular-foundation/) for the Foundation 5 JS plugins, written as Angular directives.

But yeah, we're definitely looking into ways to make the components more consistent between the two frameworks.

**Comment by etcook** [comment]
@gakimball Are there no conflicts in terms of naming, etc? Can I really just include the entire F4S CSS, or are you meaning to add it component by component manually?

Thanks!

**Comment by gakimball** [comment]
Obviously components with the same names conflict (labels, tabs, etc.), but there is one example of a component with the same name but two very different purposes in the two frameworks: panels. In Sites, `.panel` is just a colored box, but in Apps, it's the off-canvas component.

To get around this, we're looking for a name to replace "panel" in the next version of Sites. It's probably going to be "callout", since we're also combining panels and alerts into one CSS component.
