### ISSUE TITLE
Foundation for Apps Breakpoint guide missing

### ISSUE THREAD

**Issue by yashilanka** [zurb/foundation-apps#458]
Hi i couldn't find any breakpoint guide in the doc. please check that. if it is missing. please add it. for now can you explain what are the breakpoint is. is it 

small-down,
small,
small-up,
medium-down,
medium, 
medium-up,
.......
 etc...

and also foundation for app grid mess with the ipad air. grid not working. but android and desktop work well.

**Comment by gakimball** [comment]
For sure, I'm going to write one today. Here's a very brief overview.

```scss
// You can use any named breakpoint in the $breakpoints map
@include breakpoint(small) { } // Small and up
@include breakpoint(medium only) { }
@include breakpoint(medium down) { }

// You can also use px, rem, or em values, which are all converted to em
@include breakpoint(400px) { }
@include breakpoint(60rem down) { }
```

As for your grid issues, what version of iOS are you on? We just had a round of QA for iOS 7 and 8, and everything seemed fine.

**Comment by yashilanka** [comment]
Thanks can't wait to see the complete guide. i'm having those issues for iOS 8.1.3. and its all messed up. but for the desktop it's all good like charm..and one thing i want to know. i'm a UI/UX and frontend developer. currently i'm evolving to make and develop a Big Enterprise grade application by using foundation for apps. the reason is it's grid system. i like the way it works. using flex box and other stuff. but i have one problem. in our company backend developers are using ASP.Net MVC for the server site data and communication. so they want to use this grid system without angular ui routing but take all other angular awesome features. and they want to use ASP.Net MVC routing. so my question is how to use this framework without angular ui routing. or is it ok to use css grid only. or is there any other solution to fix this.

**Comment by gakimball** [comment]
About half of the components, most importantly the grid, will work without Angular or even JavaScript. So you could drop in the CSS for the basic components and it would work fine.

It's also possible to use Angular without any of the routing stuff, which is to say you can use Angular for things that aren't single-page apps. If you want to keep your backend largely the same, where ASP.Net is generating and serving HTML to the client, that's the way to go.

If you still wanted the single-page app feel, you'd have to do a fair amount of refactoring on the back-end. To make a SPA framework work with APS.Net, Rails, etc., the server-side framework has to essentially become an API. Because Angular does all of the templating work, the server then just serves up data as JSON, which the client compiles into HTML.

**Comment by gakimball** [comment]
Here's the page: <http://foundation.zurb.com/apps/docs/#!/media-queries>

**Comment by yashilanka** [comment]
Thanks
