### ISSUE TITLE
zf-open - cursor hand

### ISSUE THREAD

**Issue by moondawg69** [zurb/foundation-apps#473]
Example: http://foundation.zurb.com/apps/app-templates/productivity/#!/

Open profile for off canvas panel, no hand cursor on Profile or Projects.

**Comment by gakimball** [comment]
We fixed this in 1.0.3 (53d5952802e7d7da667c3fb19f73e0a39bc0591e), so now all `<a>` elements, not just ones with an `href` attribute, get the pointer cursor. Since there are no `href`s in Angular apps, browsers weren't applying the proper cursor to elements that are technically links.

The templates are all being updated right now, and they'll use the latest version of the framework when they're done.
