### ISSUE TITLE
Masonry layout style using grid blocks

### ISSUE THREAD

**Issue by laurent-le-graverend** [zurb/foundation-apps#492]
It is maybe missing from the documentation, a good point of using flexbox grid is to achieve fancy stuffs!

I didn't succeed to have a **masonry layout** with grid blocks (aka Pinterest style).
Is there any way do achieve this?

**Comment by gakimball** [comment]
There is, but there are two caveats. [Here's a Codepen](http://codepen.io/gakimball/pen/ZYogmK) that illustrates it.

The entire container flows as columns, and it's told to wrap, hence `flex-flow: column wrap`. Note the numbering of the items: it goes *vertical*, not *horizontal*. You can't make the HTML order horizontally, because the flex container is flowing vertically.

The other caveat is that the container in this example has a defined height. This creates the boundary that forces the child elements to wrap to the next column. Try removing `height: 350px;` from the `.box` selector—all of the child elements will just stack vertically, because now they have no reason to wrap.

So yes, there is a way to do a Masonry layout in Flexbox, but unfortunately it isn't perfect.
