### ISSUE TITLE
Tables, pagination and etc.

### ISSUE THREAD

**Issue by listepo** [zurb/foundation-apps#494]
Why not have all the features Foundation 5 in  Foundation Apps? for example tables, pagination and etc.

**Comment by gakimball** [comment]
We're trying to find a good solution for that right now, as there are plenty of components you could see being identical between the two frameworks, like panels, pagination, tables, and so on.

We're working on Foundation 6 right now, where we're trying to simplify a lot of components, so at the very least I think we'll wait until that framework is closer to completion. I wouldn't necessarily want to import any Foundation 5 components, since the codebase for them is a year and a half old.

**Comment by listepo** [comment]
thanks for an answer
