### ISSUE TITLE
All width and height images attributes are now overwritten from CSS

### ISSUE THREAD

**Issue by laurent-le-graverend** [zurb/foundation-apps#504]
https://github.com/zurb/foundation-apps/commit/ba78792c5373b4508795bccf6bdbb12297465a57

The commit above brings a lot of issues since it forces every single image to be displayed as 100% of their container if they do not override this rule explicitly, in CSS.

`<img src="..." width="50" height="50">`
This is no longer working; the width will be 100%, and the height still 50px, no need to explain why that this image won't look good ;-)

**Comment by gakimball** [comment]
This change fixes a pretty bad issue with images and flexbox in Firefox, but you're right that it may be too sweeping of a change, especially since the specificity is higher than one class (`.grid-content img`).

We've seen the issue crop up multiple times now, but we can also just implement the fix manually in those areas.

**Comment by gakimball** [comment]
Reverted with this commit: f9dafb5527c08910d97b4b53fa92aef573c2fab9
