### ISSUE TITLE
Feature request: swipe reveal functionality

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#513]
I'm pretty sure this can be achieved using a combination of F4A components and custom code, but I suspect it is a basic enough app feature that it should have its own F4A component.  The request is to allow a user to swipe a block (any direction) and have it reveal a set of options to perform on that block.  I did some searching and found an [example here](http://www.teehanlax.com/blog/reproducing-the-ios-7-mail-apps-interface/) that shows an animation of what I mean (scroll to the bottom of the tutorial).  All the components are there in F4A (panel/block swiping, animations on panel/block, menu bar to reveal in place of moved panel/block), the wiring just needs to be hooked up to make it easy for a developer to hook into their app.

**Comment by gakimball** [comment]
We'd like to do more with the touch gestures, so this is definitely an interesting idea. Unfortunately we can't do the 1:1 swipe/reveal that a native app can, but I think most developers who work on web apps understand that. (The libraries do exist but they're fairly complex, and might not work well in a framework where we have to provide generic solutions.)

**Comment by soumak77** [comment]
@gakimball Could you explain the challenges with web apps just for my own understanding?

**Comment by gakimball** [comment]
So most touch libraries like Hammer, or the stuff built into Angular or Zepto, are not 1:1, which means you can't hold your finger mid-swipe, and move it around and have the UI element move with it. That requires a lot of math and DOM manipulation that's kind of expensive to calculate.

For example, we have the `zf-swipe-close` directive in Foundation for Apps, which lets you close a modal, panel, etc. with a swipe instead of a click/tap. It's a one-time action, though—you do the swipe, and then the element animates out. You can't swipe slower or faster to change how the animation plays; it just runs in response to the swipe.

Compare this to iOS or Android, which has a lot of those more fluid gestures built-in. And there are plenty of developers who write their own custom animations for their apps. Tweetbot for iOS is a great example. The web doesn't quite yet have the means to get that kind of fidelity out of motion. There are folks who are trying really hard, but the performance isn't quite there.

**Comment by soumak77** [comment]
@gakimball Thanks for the breakdown.  I'm not quite sure you need that functionality to implement the swipe/reveal feature I have in mind, though if you do, perhaps you could help me understand.  What I have in mind is that you would swipe in one direction on an element, that element would then move in the direction swiped and stop after a specified distance.  The ability to swipe/reveal is an all or nothing action, so your top element either doesn't move or animates a specified distance and stops.  Under that element is another hidden element which is revealed.  It's basically an off-canvas for a single block.

**Comment by soumak77** [comment]
BTW, the link provided in my original post was just to visually demonstrate what I was implying with my feature request and why the feature might be useful.  The link was not meant to provide details in terms of implementation, though I'm glad you provided clarity on the subject for my understanding.

**Comment by soumak77** [comment]
I think this can be achieved fairly easily with just one more addition to F4A.  With v1.1 I can make it so that on the click of an element a menu option animates in from the right.  I just need the ability to make it so that on the swipe of the element in a specific direction, the same thing happens as if it were clicked.  I created 4 directives to achieve this: **zf-swipe-left**, **zf-swipe-right**, **zf-swipe-up**, **zf-swipe-down**.  Each directive takes an expression like ng-click and runs the expression when the element is swiped in the specified direction.

How do I create a PR for this without it combining with my existing PR?

**Comment by gakimball** [comment]
@soumak77 If you have the feature in a different branch of your fork, you should be able to open a PR with that specific branch.

If you don't have them in separate branches, I'd recommend making a new branch that compares against *this* repo's master branch, and cutting/pasting the feature in there, just so the PR is as clean as possible.

**Comment by soumak77** [comment]
@gakimball I'm doing everything on one branch (thus the reason 2e14f63c57e4541f30f62e65d4e0b6ecec68a8f0 was added to #539 instead of its own PR).  I'll move this code over to another branch and submit the PR when I find the time.  Thanks!
