### ISSUE TITLE
No animation on firefox

### ISSUE THREAD

**Issue by aga-glabala** [zurb/foundation-apps#524]
Hi, 
I build application using your Foundation for Apps. Your new grid is totally awesome, but I found out that is very slow on firefox. Every reflow of application takes about 200ms. This cause animation lag even in your example apps. 
Check out this: http://foundation.zurb.com/apps/app-templates/travel/#!/photos. When I click on Reviews or Listing in chrome there is nice animation, in firefox there is lag, flash and new screen :(

I use 36.0.1 version of firefox for ubuntu, but I checked on mac and found out same issue. 

According to this: http://updates.html5rocks.com/2013/10/Flexbox-layout-isn-t-slow the slowest part is align-items: stretch, which is default value for every .grid-block element.

**Comment by gakimball** [comment]
View animation recently got an overhaul (#386), and it's now way more robust and stable. We were able to pretty thoroughly test it in all of the browsers we support as well. It'll be in version 1.1, which we're trying to get out on Friday.

The `align-items: stretch` thing is interesting. We use that to ensure that columns in a horizontal grid are all equal-height, since `height: 100%` tends to not cut it. But we could give it another look, also, if it's a performance hit.

**Comment by aga-glabala** [comment]
Hi, 
that's good news :) I pulled newest master but I'm afraid that reflow action on my Firefox fell into some neverending loop. Maybe I did something wrong - I will wait for stable 1.1 version. Thanks!
