### ISSUE TITLE
(Potential) issue with modal component path?

### ISSUE THREAD

**Issue by mattgrande** [zurb/foundation-apps#555]
So, some upfront info:

1. I'm using HTML5 routes (eg, /whatever rather than /#!/whatever)
2. I'm using "old school" routes through the `$stateProvider`, rather than Front Matter, so I can do an auth interceptor (See also #387, #501).
3. I did those two changes, and updated to 1.1, within the past 24 hours, so it's entirely possible this is something I did.

If I'm using a modal on a page with a path like `/resources`, everything works fine. However, if I'm using it on a path like `/resources/something_else`, I get this message in my console:

    GET http://localhost:8080/resources/components/modal/modal.html 404 (Not Found)
    Error: [$compile:tpload] Failed to load template: components/modal/modal.html

I _think_ this is due to this line (https://github.com/zurb/foundation-apps/blob/master/js/angular/components/modal/modal.js#L42):

    templateUrl: 'components/modal/modal.html',

because if I add a / to the start

    templateUrl: '/components/modal/modal.html',

everything works fine.

If people agree, I can issue a pull request?

**Comment by mattgrande** [comment]
Has anyone had a chance to take a look at this?

**Comment by gakimball** [comment]
This will fix components not loading properly in HTML5 mode, but it would affect apps that still use hash bangs, but also run in a subdirectory. In hash bang mode, the relative component paths are always relative to the `index.html` file of the app, no matter what route you're on. If this was changed to an absolute path, it would look be looking in the wrong place.

We've started distributing a pre-compiled templates file, and our project template now pre-compiles templates instead of loading all those HTML files separately. Would that method get around this issue?

**Comment by mattgrande** [comment]
I'm not sure if that would get around that issue (still haven't had my morning coffee), but could you make the root configurable? Have it `''` by default, so others can override it to `'/'` if necessary?

**Comment by jeanieshark** [comment]
@mattgrande I think that the way that we're compiling the templates now using the $templateCache provider solves your issue. Can you make you're including `    <script src="assets/js/templates.js"></script>
` in your index.html file and see if you're still running into the same issue?

**Comment by zurbchris** [comment]
Closing this due to lack of feedback. If anyone else is having an issue with relative/absolute pathing, please open a new issue.
