### ISSUE TITLE
off-canvas-layout mixin not working

### ISSUE THREAD

**Issue by alexandreogrodovski** [zurb/foundation-apps#581]
Hello my friends.

I'm writing a customized class for a responsive off-canvas. The idea is to position it at the bottom on small screens and at the top on medium and larger. The problem is that off-canvas-layout mixin seems not to be working.

I noticed that .left class is always automatically applied, and its styles are taken into account.

Here is the HTML:
```
<div zf-offcanvas id="menu" class="custom-off-canvas"></div>
<div class="grid-frame">
<div class="grid-content">
  <a zf-toggle="menu" class="button">Toggle</a>
</div>
</div>
```
And here is the CSS:
```
.custom-off-canvas {
    @extend %off-canvas;
	@include off-canvas-layout($position: bottom);
	@include breakpoint(medium){
		@include off-canvas-layout($position: top);

		/* This style is correctly applied */
		@include off-canvas-style($background: #0F0);
	};
}
```
Any ideas?

Thank you.

**Comment by gakimball** [comment]
This is something we haven't fully addressed yet, so now's a good time to. Some of the components have default classes and animations applied. Panels will have this issue also.

Maybe we can switch up the logic so that if you omit the `position` attribute, it doesn't add anything? In our examples we always include it, even though it does have a default value of `left`.

**Comment by alexandreogrodovski** [comment]
I guess it is the solution @gakimball.

Thank you for your reply.

**Comment by gakimball** [comment]
Opened #589 since this is relevant to multiple components.
