### ISSUE TITLE
Implement an official React js Brench

### ISSUE THREAD

**Issue by Agamennon** [zurb/foundation-apps#587]
implement this amazing idea using React, angular is ok but its on the way out, you guys will need to re-implement in angular 2, i suggest going Ract, its perfect for this!.

**Comment by gakimball** [comment]
I don't know that you can definitively *prove* that Angular is on its way out just yet ;) Either way, a v2 of this framework is still a way off, so we'll cross that bridge when we get there. But to be sure, the opportunity cost of sticking with Angular vs. switching to another framework are about the same, because either way we have to learn something new.

**Comment by zimt28** [comment]
V2 would be a chance to make foundation for apps as framework agnostic as possible (https://github.com/zurb/foundation-apps/issues/136). Having such a version would make it easy to build Angular and React versions upon.

**Comment by gakimball** [comment]
@zimt28 Are there any examples in the wild of people doing this? Writing pure classes and then hooking them into multiple libraries?

**Comment by soumak77** [comment]
@gakimball I believe the design of the library doesn't really matter so long as there is a standard API. Integrating the library into angular, react or anything else would be the same has having to integrate a JS library like hammer, iconic or any others that F4A uses. Not everything would need to be converted to pure JS. Some features like tabs don't really make sense to convert the JS code since most of it is framework dependent. The styling would be provided by the SCSS library and animations with the motion UI module.
