### ISSUE TITLE
Without Angular

### ISSUE THREAD

**Issue by listepo** [zurb/foundation-apps#591]
Why not make a foundation app is independent of the framework? This allows you to use it on Emberjs, Backbone.js, Angular2  and other

**Comment by AntJanus** [comment]
@listepo 90% of the functionality in FA is very simple: add "is-active" to active an element, and use other classes to modify component behavior. You can easily rip out the styling from FA and wire it up with any other framework.

As far as routing goes, that's Angular specific; however, you could still use the front-end router (the Gulp plugin) to create an object and parse it for your favorite router as well.

However, there are some forks that work with other frameworks in the [resource section](https://github.com/zurb/foundation-apps/wiki/Resources) if you'd like to check that out.

**Comment by gakimball** [comment]
Like @AntJanus said, all of the components are generally framework-agnostic. Half of them also work without any JavaScript, most critically the Flexbox grid. You can install the Bower or npm package and just drop in the Sass files (or compiled CSS).

The reason we didn't write a wrapper around plain JS plugins is because then we lose some of the benefits of the framework itself. That being said, hopefully our components can be flexible enough to be dropped into any JS framework. For example, Motion UI will eventually be a standalone library, and it'll be way more configurable. Then you could use it with, say, Ember's Liquid Fire, in addition to ngAnimate.

We don't have a timeline for a v2 of a framework, but when that time rolls around we'll probably be reassessing how the framework is built, since Angular 2 is a thing.
