### ISSUE TITLE
scrollbar when using open sans

### ISSUE THREAD

**Issue by philippeluickx** [zurb/foundation-apps#626]
Hey,

Just noticed that a simple grid-content displays a scrollbar in combination with a shrinked grid-content. Text is also cut off This happens with Open Sans font, not with the standard font.

        <div class="grid-block vertical">
        		<div class="grid-block extra-margin">
        			<div class="grid-content">
        				<strong>asdf asdf jjj ggg</strong>
        			</div>
        			<div class="grid-content shrink">
        				<em>asdfa jjj kkk lll mmm qqq</em>
        			</div>
        			<div class="grid-content shrink">
        				asdfsadf
        			</div>
        			<div class="grid-content shrink">
        				<a href=""><i class="mdi mdi-close"></i></a>
        			</div>
        		</div>
        </div>

![screenshot](https://cloud.githubusercontent.com/assets/836866/7725864/f6a14df6-ff06-11e4-8254-6a582e911cb0.png)

**Comment by philippeluickx** [comment]
Just checked, the shrink has nothing to do with it. When I remove the shrink from the other grid-content elements, they all get a scrollbar.

**Comment by gakimball** [comment]
We patched the shrink behavior of grid elements to be `overflow: visible`, meaning they'll never have a scroll bar (see here: b44df9ee31e899a74a2dd2ff2d61e4b3fb096b58). The fix is in master, but hasn't landed in a stable release yet. We should have a patch version out soon.

In the mean time, you can patch this behavior yourself by adding `overflow: visible` to grid elements you know are shrinking.

Content blocks are always `overflow: auto`, meaning they get a scrollbar if the content is taller than the container. If your blocks are really short (which it looks like they might be, based on the screenshot), there's a good chance they get a scroll bar. You can disable scrolling by adding the `.noscroll` class to the element.

**Comment by philippeluickx** [comment]
Thanks for the elaborate explanation, solutions and pointer to patch! Good job on the framework, loving it!

**Comment by gakimball** [comment]
Thanks! :)
