### ISSUE TITLE
Cant scroll vertically when mouse pointer is in a block that scrolls horizontally

### ISSUE THREAD

**Issue by sgraham3311** [zurb/foundation-apps#630]
You can see this issue on any of the foundation for apps documentation pages that have a code block. Move the mouse pointer in to the code block and you wont be able to scroll the page vertically using the mouse wheel .

How can I get around this and scroll the full page or parent when the mouse is in the horizontally scrollable block.

I need it to work like this. http://www.quackit.com/html/codes/horizontal_scroll.cfm

**Comment by gakimball** [comment]
We tested this in multiple browsers to be sure, and I don't think anything we can do will fix it. Foundation for Apps projects are built with a series of scrolling boxes—the window itself never scrolls.

It seems that when you try to scroll a box in a direction it can't scroll, that scroll event goes straight to the window, instead of the next scrollable parent. If you're on a Mac, you can see the rubber-banding effect when you scroll a code example in the docs up and down. It's trying to scroll the window, instead of the scrolling box its inside.

So we determined this to be a browser issue, and there isn't really anything we can do about it.

**Comment by sgraham3311** [comment]
ui-grid seems to have figured out how to bubble the event up to the parent when you reach the end of a vertical scroll in a child container. I am using that with foundation-apps, although I am not sure if it will have the same problem when the child container has only a horizontal scroll. 

I guess the issue is foundation doesn't scroll the window it self just the grid-frame and grid-blocks.

thanks

**Comment by gakimball** [comment]
Right, inner containers with a vertical scroll will continue scrolling the next parent up when they reach the bottom. The same doesn't apply to horizontal scrolling containers.

Are you saying ui-grid fixes the horizontal scrolling issue?

**Comment by sgraham3311** [comment]
No I have not confirmed this yet.

**Comment by gakimball** [comment]
@sgraham3311 Hm, well let me know if you come across a solution that gets around this, because it seems like a browser or operating system issue.
