### ISSUE TITLE
Issue with smooth scroll 3rd party libraries

### ISSUE THREAD

**Issue by philippeluickx** [zurb/foundation-apps#682]
I am trying to get smooth scrolling to work and configured both
https://github.com/oblador/angular-scroll and https://github.com/d-oliveros/ngSmoothScroll

Neither works. I tried them in a clean FA project, but nothing seems to happen.

As on their own they work and both flunk when integrated into FA, I figured it could have to do with FA?

Thanks!

**Comment by gakimball** [comment]
If the plugin attaches the smooth scrolling behavior to the window, nothing will happen, because Foundation apps don't scroll on the window—they scroll on inner `<div>` elements.

Presumably you'd need to configure the plugin to attach to grid elements. You can target `.grid-content` specifically, because these are the scrolling elements.

**Comment by philippeluickx** [comment]
Yup, that seems to work! Thanks for the pointer.
Having a grid-content inside a grid-container didn't work. Having the scroll-container at the encompassing grid-content seemed to do the trick!
