### ISSUE TITLE
[ANNOUNCEMENT] Version 1.2.0 this Friday

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#725]
Hey guys, we're going to be releasing version 1.2.0 of Foundation for Apps on Friday. We'll be reviewing every issue and pull request this week, QAing on Thursday, and tagging a new release on Friday. If you have any thoughts on critical issues that need to be resolved, let us know!

**Comment by gakimball** [comment]
@soumak77 Thoughts?

**Comment by JesusisFreedom** [comment]
Amazing :+1: :+1:

**Comment by soumak77** [comment]
I would love to see the following changes in 1.2.  I've been using all these changes in production code for the past 6+ months.  All changes to exposed APIs are backwards compatible:
- PR #549 - Interchange Directives
  - `FoundationMQ` service changes
    - The changes I've made to the `FoundationMQ` service have proven to be quite useful so that I can perform media queries in code as shown below.  The methods use named queries so to allow user defined values.
      - `FoundationMQ.matchesMediaOnly("small"); // checks if device is small only`
      - `FoundationMQ.matchesMedia("medium"); // checks if device is medium or higher`
  - Interchange Directives
    - I absolutely love how these directives work.  It makes it so simple to tag an element with a specific media query.  It also removes the need for additional DOM elements as is required by the current interchange mechanism `zf-interchange`.
- PR #730 - Animation Promises 
  - Changes allow chaining animations so they can be performed one after another.  The changes use the `$q` service to handle the promises.
- PR #704 - Add angular support and multiple runs
  - Allows dynamic routing module to be run multiple times by appending to the routes file if it already exists.  File will be created if it doesn't already exist.
  - Removes the dependency on the global variable `foundationRoutes` when angular support is enabled.  Uses the `angular.module('foundation.dynamicRouting').config()` method to add routes.

Those have proven to be the most useful changes I've made to the framework.  While I think PR #551 (Swipe Directives) is a really promising feature, there is much work to do still to get it working flawlessly, so I wouldn't suggest merging the PR for 1.2. I don't currently use those directives in production code, though I will need to for a product I have to release by September, so by then I'll have all the kinks worked out.

**Comment by gakimball** [comment]
@soumak77 Awesome, thank you! We plan on reviewing every PR before Friday. Are there any particular bugs that you think would be critical? (Granted, this isn't a one-and-done thing, we'll be doing more bug-fixing in the future. But this is our first patch in a *while* so we want to make it count.)

**Comment by soumak77** [comment]
@gakimball There aren't any critical bugs that I've seen that I haven't already fixed myself in the framework.  I think for the most part I've created PRs for things I've fixed in the framework along the way.  I'll go through the changes I've committed to my company's forked repo of F4A that we use in production and reply shortly with the changes that haven't made it into the F4A master yet.

**Comment by soumak77** [comment]
These are the only two bug fixes I've made that aren't yet in the framework:
- Check for null scope during SVG injection
  - https://github.com/fiboacademy/foundation-apps/commit/2acffdc845e4f662c04fa2ad1a0e6f8290e66a4b
- Check scope and element during modal destroy
  - https://github.com/fiboacademy/foundation-apps/commit/d6273a97ef299b8600cbe4f5db237aec19620761
  - there was a discussion as to whether or not these checks were needed when https://github.com/zurb/foundation-apps/pull/645 was merged and it was determined they were not, however, in practice, I've found they are needed

**Comment by soumak77** [comment]
In terms of existing issues, it would be nice to see the following resolved:
- https://github.com/zurb/foundation-apps/issues/430
  - This is specific for off-canvas, though I've found it would be useful for panels as well.  I simply add the necessary click handlers to other elements in the app so clicking on them cause the panel/off-canvas to close, but it would be nice to see an integrated option so I don't have to worry about which exact elements need the click handlers.  I would like to be able to simply flag the off-canvas/panel component as needing to close when clicked outside.
- https://github.com/zurb/foundation-apps/issues/484
  - It would be nice to remove my dependency on `Modernizr` as I'm only using it for F4A support detection.
- https://github.com/zurb/foundation-apps/issues/578
  - This is easily solved by adding one line of css in my app, though a solution via a framework css class would be nice
- https://github.com/zurb/foundation-apps/issues/672
  - This one is just plain annoying
- https://github.com/zurb/foundation-apps/issues/699
  - I had to remove all range sliders in my app due to this issue.  Still can't figure out what exactly is happening.

**Comment by dexster** [comment]
Would love to see this one fixed. Annoying that I have to handle animations manually when this is built-in  
* Modal animation-in motion class not animating #616

**Comment by agianikas** [comment]
Will this update include Angular 1.4?

**Comment by gakimball** [comment]
@agianikas Yes, we'll be testing in Angular 1.4. The `bower.json` will likely be a version range, to allow for 1.3 or 1.4.

**Comment by zurbchris** [comment]
@soumak77 in reference to [fiboacademy@d6273a9](https://github.com/fiboacademy/foundation-apps/commit/d6273a97ef299b8600cbe4f5db237aec19620761) and #645, with the `$timeout` method you were still having errors if `!scope` or `!element`?

**Comment by soumak77** [comment]
@zurbchris Please disregard my comments about that change.  The head of my repo has the same code for modal destroy as F4A master and I haven't experienced any issues.

**Comment by zurbchris** [comment]
awesome

**Comment by soumak77** [comment]
I would like to see https://github.com/zurb/foundation-apps/issues/572 resolved at some point as well.  I ended up getting the functionality I needed, but my solution is a hack at best.

**Comment by gakimball** [comment]
We put out 1.2.0 on Friday. Thanks so much everyone for recommending bugs and pull requests for us to look at! [The changelog](https://github.com/zurb/foundation-apps/releases/tag/v1.2.0) includes an overview of our plans for 1.3, which will include a few deprecations, so be sure to take a look.

If there's anything that needs done for a patch to 1.2, let us know and we'll get to it. Thanks! :)
